name: CI

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'

      # install protoc
      - uses: arduino/setup-protoc@master

      - run: yarn

      - run: yarn test --coverage

      - run: yarn lint

      - uses: codecov/codecov-action@v1

      - run: yarn publish --patch
        if: ${{ github.event_name == 'push' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
